Updates the h function to allow falsy values on data attributes
mubanjs/muban-template pull request #4
Opened 2022-02-28 22:51 UTC by jspolancor

- Updates the h function to allow false values on data attributes
- Creates the cleanFalsyBooleans function to mutate html props
- Updates tests to reflect the changes

2022-02-28 23:00 UTC, ThaNarie requested changes
Besides the small comments, I would like to mention:

* The commit messages are written in the wrong "tense" (`updates` should be `update`)
* I'm missing the updated `README` (as specified in the task list of the original ticket).
* It would also be nice to have an accompanied PR on the muban repo to update the docs.

2022-02-28 23:00 UTC, ThaNarie commented on src/lib/mtl.ts
> +  Object.entries(stringifiedProps).forEach(([key, value]) => {
I think a `.entries` > `.map` > `.fromEntries` is a bit nicer here (instead of the `stringifiedProps` mutation inside the loop`

2022-02-28 23:00 UTC, ThaNarie commented on src/lib/mtl.ts
> +export function cleanFalsyBooleans(props: Record<string, any>): Record<string, any> {
`unknown` instead of `any` would probably work here as well.

2022-02-28 23:00 UTC, ThaNarie commented on src/lib/mtl.ts
> +  const mutatedProps = cleanFalsyBooleans(props);
Maybe naming wise, something like this?

* `processFalsyBooleanProps`
* `processedProps`

2022-03-03 17:19 UTC, jspolancor commented on src/lib/mtl.ts
> +  Object.entries(stringifiedProps).forEach(([key, value]) => {
Fixed

2022-03-03 17:22 UTC, jspolancor commented on src/lib/mtl.ts
> +export function cleanFalsyBooleans(props: Record<string, any>): Record<string, any> {
Fixed

2022-03-03 17:22 UTC, jspolancor commented on src/lib/mtl.ts
> +  const mutatedProps = cleanFalsyBooleans(props);
Fixed

2022-03-03 17:23 UTC, jspolancor commented
> Besides the small comments, I would like to mention:
> 
> * The commit messages are written in the wrong "tense" (`updates` should be `update`)
> * I'm missing the updated `README` (as specified in the task list of the original ticket).
> * It would also be nice to have an accompanied PR on the muban repo to update the docs.

The Readme was updated, I'll create the PR to the muban repo in a moment

2022-03-03 18:14 UTC, ThaNarie approved these changes

2022-09-20 17:56 UTC, merged